#Screen window
WINDOW_WIDTH, WINDOW_HEIGHT = 800, 600

#Circuit
CIRCUIT_WIDTH, CIRCUIT_HEIGHT = 400, 400
CIRCUIT_X, CIRCUIT_Y = (WINDOW_WIDTH - CIRCUIT_WIDTH) // 2, (WINDOW_HEIGHT - CIRCUIT_HEIGHT) // 2
ENTRY_LANE_X = 370
EXIT_LANE_X = 430
LANE_Y = 0

#Vehicles
VEHICLE_SPEED = 2
VEHICLE_SIZE = 5